{'name': 'Bảng lương Forher',
 'version': '18.0.1.0.0',
 'summary': 'Quản lý tính lương cho Forher',
 'category': 'Nhân sự',
 'author': 'Forher IT',
 'depends': ['base',
             'mail',
             'hr',
             'hr_holidays',
             'forher_contract',
             'forher_attendance',
             'forher_hr_employee'],
 'data': ['security/payroll_security.xml',
          'security/ir.model.access.csv',
          'data/ir_sequence_data.xml',
          'data/payroll_rules_data.xml',
          'views/salary_rule_views.xml',
          'views/payroll_config_views.xml',
          'views/payslip_run_views.xml',
          'views/payslip_views.xml',
          'views/payroll_menus.xml',
          'wizard/payroll_import_wizard_views.xml'],
 'installable': True,
 'application': True}
